<!doctype html>
<html lang="en">
  <head>
    <title>Statement hotel</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900|Rubik:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/bootstrap.css">
    <link rel="stylesheet" href="assets/css/animate.css">
    <link rel="stylesheet" href="assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="assets/fonts/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/fonts/fontawesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/magnific-popup.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 
    <!-- Theme Style -->
    <link rel="stylesheet" href="assets/css/style.css">
    <!-- Google font -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">
  <!-- Custom stlylesheet -->
  <link type="text/css" rel="stylesheet" href="assets/css/404.css" />
  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
  
  </head>
  <body>
    
    <header role="banner">
     
      <nav class="navbar navbar-expand-md navbar-dark bg-light">
        <div class="container">
              <a class="navbar-brand" href="index.html">
              <img src="images/<?php echo settings(1)['logo'] ?>" width="200" height="120" class="d-inline-block align-top" alt="<?php echo settings(1)['hotel_name']  ?>" title="<?php echo settings(1)['hotel_name'] ?>">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse navbar-light" id="navbarsExample05">
            <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
              <li class="nav-item">
                <a class="nav-link active" href="index.php" style="color:#f4e181">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="rooms-categories" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="rooms.html" style="color:#f4e181">Rooms</a>
                <div class="dropdown-menu" aria-labelledby="rooms-categories">
                  <a class="dropdown-item" href="rooms.html" style="color:#f4e181;">All Rooms</a>
                  <a class="dropdown-item" href="room1.html" style="color:#f4e181;">Presidential Suite</a>
                  <a class="dropdown-item" href="room2.html" style="color:#f4e181;">Business Suite</a>
                  <a class="dropdown-item" href="room3.html" style="color:#f4e181;">Classic Room</a>
                  
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="facilities.html" style="color:#f4e181" >Facilities</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="gallery.html" style="color:#f4e181;">Gallery</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="contact.html" style="color:#f4e181;">Contact</a>
              </li>
               <li class="nav-item ">
                <a class="nav-link " href="booknow.html" style="color:#f4e181;"><span>Book Now</span></a>
              </li>
            </ul>
            
          </div>
        </div>
      </nav>
    </header>
   
    